version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Libros_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db  # Nombre del servicio de MySQL en docker-compose.yml
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data: