apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-php
  template:
    metadata:
      labels:
        app: api-php
    spec:
      containers:
      - name: api-php-container
        image: api-php
        ports:
        - containerPort: 80